// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLyfZyODOfX7cj_fFUofiAem_4UTjBfK0',
    appId: '1:975357426542:web:5243999616545357ed5f7f',
    messagingSenderId: '975357426542',
    projectId: 'chat-app-6fa7f',
    authDomain: 'chat-app-6fa7f.firebaseapp.com',
    storageBucket: 'chat-app-6fa7f.appspot.com',
    measurementId: 'G-9VQHGV0MKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7uc3o8kUA_Hjqy-eOBWv4fhPWJlGyyEQ',
    appId: '1:975357426542:android:b459cb7c4663df5bed5f7f',
    messagingSenderId: '975357426542',
    projectId: 'chat-app-6fa7f',
    storageBucket: 'chat-app-6fa7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OrQr_nFRX2XffPcu7XuelNLPhFAgTgc',
    appId: '1:975357426542:ios:81e31aaa84984d00ed5f7f',
    messagingSenderId: '975357426542',
    projectId: 'chat-app-6fa7f',
    storageBucket: 'chat-app-6fa7f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OrQr_nFRX2XffPcu7XuelNLPhFAgTgc',
    appId: '1:975357426542:ios:81e31aaa84984d00ed5f7f',
    messagingSenderId: '975357426542',
    projectId: 'chat-app-6fa7f',
    storageBucket: 'chat-app-6fa7f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLyfZyODOfX7cj_fFUofiAem_4UTjBfK0',
    appId: '1:975357426542:web:008d0708c0e9fadaed5f7f',
    messagingSenderId: '975357426542',
    projectId: 'chat-app-6fa7f',
    authDomain: 'chat-app-6fa7f.firebaseapp.com',
    storageBucket: 'chat-app-6fa7f.appspot.com',
    measurementId: 'G-0T97ZZ7RWN',
  );

}